### ISSUE TITLE
Too strong `root` check

### ISSUE THREAD

**Issue by vanrein** [flyingrhinonz/nftwatch#1]
You are using `getpass.getuser()` to see if the login user is `root`.  This is too strict, as one might have used `su` or `sudo` and have an effective uid 0.  Also, I would suggest to match a uid, not a username as that is more of a convention than kernel-coded.

Suggestion:

```
-    if not getpass.getuser() == 'root':
+    if not os.getuid() == 0:
```

**Comment by vanrein** [comment]
Although I do not see a difference, I suppose `os.geteuid()` is better than `os.getuid()`.  I'm always a little confused about these "concepts" in POSIX "standards¨

**Comment by flyingrhinonz** [comment]
Done. Will be present in next commit.
With sudo it probably doesn't matter uid/euid because both are run as root. But if you're running something that set uid bit set then it helps to use euid.
