### ISSUE TITLE
Suggest making configfile optional

### ISSUE THREAD

**Issue by vanrein** [flyingrhinonz/nftwatch#2]
Since you hand over an initial configuration file, why not make it optional?

For an admin, a tool that works out of the box, as a configuration-free standalone, is convenient for chasing problems.  That's because I compare your tool to `mrt`.  If/when I would use it for live monitoring I thing I would be more tempted to fine-tune and use a configuration file.

So I'd suggest to make the loading of the configuration file optional and simply have the example file settings as defaults.

**Comment by flyingrhinonz** [comment]
Good idea. I've got all the settings as defaults in nftwatch already.
Will be present in next commit.
