### ISSUE TITLE
Crash in `PopulateWindows()`

### ISSUE THREAD

**Issue by vanrein** [flyingrhinonz/nftwatch#3]
I ran into an `IndexError: list index out of range` exception, and added test output to the code around line 1139

```
    print ('LOOPING FROM %r TO %r-1 IN ARRAY SIZED %d' % (GlobalConfig.VerticalOffset, ( GlobalConfig.VerticalOffset + GlobalConfig.ScreenHeight - 3 ), len (NftStats.FreezeSplitNftOutput) ) )
    for Looper in range(GlobalConfig.VerticalOffset, ( GlobalConfig.VerticalOffset + GlobalConfig.ScreenHeight - 3 ) ):
```

It reported

```
LOOPING FROM 0 TO 42-1 IN ARRAY SIZED 9
```

and when `Looper` reaches `9` it crashes its thread.

As you can see, this combines a small set of NFT stats with a tall window.  Yeah, users can be pathetic ;-)

**Comment by flyingrhinonz** [comment]
hmmm, I've always tested nfwatch with tons of manufactured rules in a small window to push it hard.
turns out the opposite causes bugs too.
let me look into this...

**Comment by flyingrhinonz** [comment]
Thanks for taking the time to debug and report these bugs and improvements.
Great to see others give feedback that I didn't think of.

**Comment by flyingrhinonz** [comment]
Fixed as well as exposed another bug which is also fixed.
Thanks for the bug report.
