### ISSUE TITLE
Suggestion: Add graphical bars (similar to iftop)

### ISSUE THREAD

**Issue by nis65** [flyingrhinonz/nftwatch#5]
First, thanks for that cool tool. I was just looking at some `nft list ruleset` outputs on [my debian router](https://github.com/nis65/ansible-debian-router) to see how counters evolve and then found your nice tool.

I often use `iftop` that has the displays the relative traffic with **fore/background inverted bars**. I usually set them to logarithmic scale which is usually much more useful to me. This would be really nice to have :-) in `nftwatch` too.

In addition, `iftop` also **sorts lines by amount of traffic** by default. As option, this would be nice for `nft` counters too. However, reordering lines would change the firewall semantics if read "as is", so the interpretation of reordered lines might become somewhat doubtful. In my setup, ordering by traffic *per chain* would be very helpful and the semantic implications would be well understood to me. But I am unsure whether this is generic enough to justify the effort and added complexity... :thinking:

**Comment by flyingrhinonz** [comment]
Hi,
The BPS/PPS rates are calculated between refreshes. It is possible to let the reads continue without the screen refresh and grab the outputs to populate a sorted list (sort by pps/bps , total packets/bytes, ascending/descending). These lines could be confusing without the context of chains though.

Fancy graphics, bars, etc is a lot of work for not much benefit beyond visuals.

Ordering by/within chains is more tricky as the tool doesn't have an understanding of chains, etc.

I'm really busy in the forseeable future and I doubt I'll have the time to work on this anytime soon. Let's leave this open for a while and see if someone else can take it on.
