### ISSUE TITLE
Suggestion: Ignore sets in output

### ISSUE THREAD

**Issue by Olen** [flyingrhinonz/nftwatch#6]
Hi,

Just discovered this nice tool.

I have some pretty large sets (geoip, abuseipdb etc.) and they really make the output a bit unusable, as there are tens of thousands of entries in the sets.
The content of the sets does not really add anything important to this tool, so it would be nice if it was just ignored (maybe as an option in the config).

**Comment by flyingrhinonz** [comment]
Nice idea. Let me think what else can be added to the read command and apply a config item to it.
I'm really busy right now, I don't think I'll work on this for quite some time. But I like your idea and will try to help.
